const storageKey = 'memory-everyday-events';
const groupStorageKeyBase = 'memory-everyday-groups-v1';
const zoomStorageKey = 'memory-everyday-calendar-scale-v2';
const pendingSyncKey = 'memory-everyday-pending-sync';
const authReminderKey = 'memory-everyday-auth-reminder-shown';
const calendarZoomLevels = [{ previewLimit: 2 }, { previewLimit: 2 }, { previewLimit: 3 }];
const earliestSelectableYear = new Date().getFullYear() - 5;
const latestSelectableYear = 2070;
const supabaseUrl = 'https://ojhukmhpjovwswnmxoig.supabase.co';
const supabasePublishableKey = 'sb_publishable_vTBsX9EuhLWb7LBY7PrRlQ_OjX3sw8l';
const supabaseClient = window.supabase?.createClient(supabaseUrl, supabasePublishableKey) || null;
const state = {
  selected: new Date(), showing: new Date(), pickerShowing: new Date(), dayPickerShowing: new Date(), editingEventId: null,
  calendarZoom: Math.min(2, Math.max(0, Number(localStorage.getItem(zoomStorageKey)) || 0)),
  events: readStoredEvents(storageKey), groups: readStoredGroups(groupStorageKey()), activeGroupId: 'all', editingGroupId: null, user: null, authReady: false, syncBusy: false, authMode: 'login', groupsInitialized: false
};
const $ = (id) => document.getElementById(id);
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const formatDate = (date) => new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(date);
function readStoredEvents(key) { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
function writeStoredEvents(key, events) { localStorage.setItem(key, JSON.stringify(events)); }
function userStorageKey(user = state.user) { return user ? `${storageKey}:${user.id}` : storageKey; }
function groupStorageKey(user = null) { return user ? `${groupStorageKeyBase}:${user.id}` : groupStorageKeyBase; }
function hasStoredGroups(user = state.user) { return localStorage.getItem(groupStorageKey(user)) !== null; }
function defaultGroups() { return [{ id: 'life', name: '生活表', color: 'mint' }, { id: 'course', name: '课程表', color: 'purple' }]; }
function readStoredGroups(key) { try { const stored = localStorage.getItem(key); if (stored === null) return defaultGroups(); const value = JSON.parse(stored); return Array.isArray(value) ? value.filter((group) => group && typeof group.id === 'string' && typeof group.name === 'string').map((group) => ({ id: group.id, name: group.name.slice(0, 20), color: group.color || 'blue' })) : defaultGroups(); } catch { return defaultGroups(); } }
function saveGroups() { localStorage.setItem(groupStorageKey(state.user), JSON.stringify(state.groups)); }
function fallbackGroupId() { return state.groups.find((group) => group.id === 'life')?.id || state.groups[0]?.id || 'all'; }
function eventGroupId(event) { return event.groupId === 'all' || state.groups.some((group) => group.id === event.groupId) ? event.groupId : fallbackGroupId(); }
function normalizeEventGroups() { state.events = state.events.map((event) => ({ ...event, groupId: eventGroupId(event) })); }
function pendingStorageKey(user = state.user) { return user ? `${pendingSyncKey}:${user.id}` : pendingSyncKey; }
function readPending(user = state.user) { try { const value = JSON.parse(localStorage.getItem(pendingStorageKey(user)) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
function writePending(value) { if (state.user) localStorage.setItem(pendingStorageKey(), JSON.stringify(value)); }
function save() { normalizeEventGroups(); writeStoredEvents(userStorageKey(), state.events); }
function visibleEvents() { return state.activeGroupId === 'all' ? state.events : state.events.filter((event) => eventGroupId(event) === state.activeGroupId); }
function eventsFor(date) { return visibleEvents().filter((e) => e.date === dateKey(date)).sort((a, b) => a.time.localeCompare(b.time)); }
function eventTimeLabel(e) { const time = normalizeTime(e.time) || e.time, endTime = normalizeTime(e.endTime, true) || e.endTime; return endTime ? `${time}–${endTime}` : time; }
function eventDateTime(date, time) { const [year, month, day] = date.split('-').map(Number), [hours, minutes] = time.split(':').map(Number), isMidnightEnd = hours === 24; return new Date(year, month - 1, day + (isMidnightEnd ? 1 : 0), isMidnightEnd ? 0 : hours, minutes); }
function isEventPast(event, now = new Date()) { return eventDateTime(event.date, event.endTime || event.time) <= now; }
function refreshPastEventStyles() { const now = new Date(); document.querySelectorAll('[data-event-id]').forEach((element) => { const event = state.events.find((item) => item.id === element.dataset.eventId); element.classList.toggle('is-past', Boolean(event && isEventPast(event, now))); }); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]); }
function groupName(groupId = state.activeGroupId) { return groupId === 'all' ? '总日程表' : state.groups.find((group) => group.id === groupId)?.name || '总日程表'; }
function renderEventGroupOptions(selectedId) { const fallback = selectedId || fallbackGroupId(), groups = state.groups.length ? state.groups : [{ id: 'all', name: '总日程表' }]; $('event-group').innerHTML = groups.map((group) => `<option value="${escapeHtml(group.id)}">${escapeHtml(group.name)}</option>`).join(''); $('event-group').value = groups.some((group) => group.id === selectedId) ? selectedId : fallback; }
function setGroupDrawer(open) { const expanded = Boolean(open); $('app-shell').classList.toggle('is-group-drawer-open', expanded); $('group-sidebar-toggle').setAttribute('aria-expanded', String(expanded)); $('group-sidebar-toggle').setAttribute('aria-label', expanded ? '收起日程表' : '展开日程表'); $('group-sidebar-toggle').textContent = expanded ? '‹' : '›'; }
function setActiveGroup(groupId) { state.activeGroupId = groupId === 'all' || state.groups.some((group) => group.id === groupId) ? groupId : 'all'; setGroupDrawer(false); render(); }
function renderGroups() { const list = $('group-list'), allCount = state.events.length; $('current-group-name').textContent = groupName(); list.innerHTML = `<div class="group-row ${state.activeGroupId === 'all' ? 'is-active' : ''}"><button type="button" class="group-select" data-group-id="all"><span class="group-dot all"></span><span>总日程表</span><small>${allCount}</small></button></div>${state.groups.map((group) => `<div class="group-row ${state.activeGroupId === group.id ? 'is-active' : ''}"><button type="button" class="group-select" data-group-id="${escapeHtml(group.id)}"><span class="group-dot ${escapeHtml(group.color || 'blue')}"></span><span>${escapeHtml(group.name)}</span><small>${state.events.filter((event) => eventGroupId(event) === group.id).length}</small></button><button type="button" class="group-edit" data-edit-group-id="${escapeHtml(group.id)}" aria-label="编辑${escapeHtml(group.name)}">···</button></div>`).join('')}`; list.querySelectorAll('[data-group-id]').forEach((button) => { button.onclick = () => setActiveGroup(button.dataset.groupId); }); list.querySelectorAll('[data-edit-group-id]').forEach((button) => { button.onclick = () => openGroupDialog(state.groups.find((group) => group.id === button.dataset.editGroupId)); }); }
function setGroupColor(color) { $('group-color').value = color; document.querySelectorAll('[data-group-color]').forEach((button) => { const selected = button.dataset.groupColor === color; button.classList.toggle('is-selected', selected); button.setAttribute('aria-checked', String(selected)); }); }
function openGroupDialog(group = null) { state.editingGroupId = group?.id || null; $('group-dialog-eyebrow').textContent = group ? '调整日程表' : '新的日程表'; $('group-dialog-title').textContent = group ? '编辑日程表' : '创建日程表'; $('save-group-button').textContent = group ? '保存修改' : '创建日程表'; $('delete-group-button').classList.toggle('is-hidden', !group); $('group-name').value = group?.name || ''; setGroupColor(group?.color || 'blue'); $('group-form-error').textContent = ''; $('group-dialog').showModal(); $('group-name').focus(); }
function closeGroupDialog() { $('group-dialog').close(); state.editingGroupId = null; }
function deleteEditingGroup() { const groupId = state.editingGroupId; if (!groupId) return; const eventsToDelete = state.events.filter((event) => eventGroupId(event) === groupId); state.events = state.events.filter((event) => eventGroupId(event) !== groupId); state.groups = state.groups.filter((group) => group.id !== groupId); state.activeGroupId = 'all'; save(); saveGroups(); eventsToDelete.forEach((event) => queueOperation({ entity: 'event', type: 'delete', id: event.id })); if (state.user) { state.groupsInitialized = true; queueOperation({ entity: 'group', type: 'delete', id: groupId }); queueGroupSnapshot(); queueSettingsSync(); } void flushPendingOps(); $('group-delete-confirm-dialog').close(); closeGroupDialog(); render(); }
function updateCalendarZoom() { $('calendar-screen').dataset.calendarZoom = String(state.calendarZoom); $('calendar-zoom-out').disabled = state.calendarZoom === 0; $('calendar-zoom-in').disabled = state.calendarZoom === calendarZoomLevels.length - 1; $('calendar-zoom-out').setAttribute('aria-label', state.calendarZoom === 0 ? '已是最小月历' : '缩小月历'); $('calendar-zoom-in').setAttribute('aria-label', state.calendarZoom === calendarZoomLevels.length - 1 ? '已是最大月历' : '放大月历'); }
function saveCalendarZoom() { localStorage.setItem(zoomStorageKey, String(state.calendarZoom)); queueOperation({ entity: 'settings', type: 'upsert', id: 'preferences', settings: { calendarZoom: state.calendarZoom, groupsInitialized: state.groupsInitialized } }); void flushPendingOps(); }
function renderCalendar() {
  const year = state.showing.getFullYear(), month = state.showing.getMonth(); $('calendar-month-trigger').textContent = `${year}年${month + 1}月`;
  const selected = state.selected; $('calendar-selected-year').textContent = `${selected.getFullYear()}年`; $('calendar-selected-date').textContent = `${selected.getMonth() + 1}月${selected.getDate()}日`; $('calendar-selected-weekday').textContent = new Intl.DateTimeFormat('zh-CN', { weekday: 'long' }).format(selected);
  const first = new Date(year, month, 1), start = new Date(year, month, 1 - first.getDay()), grid = $('calendar-grid'); grid.innerHTML = '';
  for (let i = 0; i < 42; i += 1) {
    const d = new Date(start); d.setDate(start.getDate() + i); const sameMonth = d.getMonth() === month, dayEvents = eventsFor(d);
    const cell = document.createElement('div'); cell.className = `day-cell ${sameMonth ? '' : 'is-other'} ${dayEvents.length ? '' : 'is-empty'} ${dateKey(d) === dateKey(state.selected) ? 'is-selected' : ''} ${dateKey(d) === dateKey(new Date()) ? 'is-today' : ''}`; cell.setAttribute('role', 'button'); cell.setAttribute('tabindex', '0'); cell.setAttribute('aria-label', `${formatDate(d)}，${dayEvents.length}项日程`);
    const number = document.createElement('span'); number.className = 'day-number'; number.textContent = d.getDate(); cell.append(number);
    const previews = document.createElement('div'); previews.className = 'day-event-previews';
    dayEvents.slice(0, calendarZoomLevels[state.calendarZoom].previewLimit).forEach((event) => { const preview = document.createElement('button'); preview.type = 'button'; preview.className = `calendar-event ${event.color || 'blue'} ${isEventPast(event) ? 'is-past' : ''}`; preview.dataset.eventId = event.id; preview.setAttribute('aria-label', `${eventTimeLabel(event)} ${event.title}`); const time = document.createElement('span'); time.className = 'calendar-event-time'; time.textContent = eventTimeLabel(event); const title = document.createElement('span'); title.className = 'calendar-event-title'; title.textContent = event.title; preview.append(time, title); preview.onclick = (click) => { click.stopPropagation(); openEventDialog(event); }; previews.append(preview); });
    if (dayEvents.length > calendarZoomLevels[state.calendarZoom].previewLimit) { const more = document.createElement('span'); more.className = 'more-events'; more.textContent = `+${dayEvents.length - calendarZoomLevels[state.calendarZoom].previewLimit}项`; previews.append(more); }
    cell.append(previews); cell.onclick = () => { state.selected = d; state.showing = new Date(d); render(); }; cell.onkeydown = (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); cell.click(); } }; grid.append(cell);
  }
  const selectedCell = grid.querySelector('.is-selected'), scroller = $('calendar-scroll'), weekdays = scroller.querySelector('.weekdays');
  const selectedIsShowing = selected.getFullYear() === year && selected.getMonth() === month;
  if (selectedCell && selectedIsShowing) {
    const viewport = scroller.getBoundingClientRect(), cell = selectedCell.getBoundingClientRect(), headerHeight = weekdays.offsetHeight + 9;
    const selectedCenterX = scroller.scrollLeft + cell.left - viewport.left + cell.width / 2;
    const selectedTop = scroller.scrollTop + cell.top - viewport.top;
    scroller.scrollLeft = Math.max(0, selectedCenterX - scroller.clientWidth / 2);
    scroller.scrollTop = Math.max(0, selectedTop - headerHeight);
  } else {
    scroller.scrollTo({ left: 0, top: 0 });
  }
}
function eventMarkup(e, card = false) { const time = eventTimeLabel(e); return `<div class="${card ? 'event-card' : 'agenda-item'} ${e.color || 'blue'} ${isEventPast(e) ? 'is-past' : ''}" data-event-id="${escapeHtml(e.id)}" role="button" tabindex="0"><span class="${card ? '' : 'agenda-time'}">${escapeHtml(time)}</span><div><strong class="${card ? '' : 'agenda-title'}">${escapeHtml(e.title)}</strong>${card ? `<small>${e.mode === 'range' ? '时间段' : `${escapeHtml(time)} 提醒`}</small>` : ''}</div></div>`; }
function bindEventDetails() { document.querySelectorAll('.agenda-item[data-event-id], .event-card[data-event-id]').forEach((element) => { const open = () => { const event = state.events.find((item) => item.id === element.dataset.eventId); if (event) openEventDialog(event); }; element.onclick = open; element.onkeydown = (keyEvent) => { if (keyEvent.key === 'Enter' || keyEvent.key === ' ') { keyEvent.preventDefault(); open(); } }; }); }
function renderAgenda() { const events = eventsFor(state.selected); $('schedule-count').textContent = events.length ? `${events.length} 项日程` : ''; $('calendar-agenda').innerHTML = events.length ? events.map((event) => eventMarkup(event)).join('') : '<div class="empty-state">这一天还没有安排，点右下角加一个吧</div>'; bindEventDetails(); }
function renderDay() { const d = state.selected; $('day-weekday').textContent = new Intl.DateTimeFormat('zh-CN', { weekday: 'long' }).format(d); $('day-year').textContent = `${d.getFullYear()}年`; $('day-title').textContent = new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric' }).format(d); const events = eventsFor(d); $('day-summary').textContent = events.length ? `今天有 ${events.length} 项安排` : '今天留给自己慢慢安排'; let html = ''; for (let h = 6; h <= 22; h += 1) { const time = `${String(h).padStart(2, '0')}:00`; html += `<div class="time-row"><span class="time-label">${time}</span><div class="time-line"></div>${events.filter((e) => e.time.slice(0, 2) === String(h).padStart(2, '0')).map((e) => eventMarkup(e, true)).join('')}</div>`; } $('timeline').innerHTML = html; bindEventDetails(); }
function render() { renderGroups(); renderCalendar(); renderAgenda(); renderDay(); refreshPastEventStyles(); }
document.querySelectorAll('.tab').forEach((tab) => { tab.onclick = () => { document.querySelectorAll('.tab').forEach((t) => t.classList.remove('is-active')); tab.classList.add('is-active'); document.querySelectorAll('.screen').forEach((s) => s.classList.toggle('is-hidden', s.id !== tab.dataset.screen)); }; });
$('previous-month').onclick = () => { state.showing.setMonth(state.showing.getMonth() - 1); renderCalendar(); }; $('next-month').onclick = () => { state.showing.setMonth(state.showing.getMonth() + 1); renderCalendar(); }; $('today-button').onclick = $('jump-today').onclick = () => { state.selected = new Date(); state.showing = new Date(); render(); };
function renderDayYearList() { const list = $('day-year-list'), selectedYear = state.dayPickerShowing.getFullYear(); list.innerHTML = ''; for (let year = earliestSelectableYear; year <= latestSelectableYear; year += 1) { const option = document.createElement('button'); option.type = 'button'; option.className = `day-year-option ${year === selectedYear ? 'is-selected' : ''}`; option.textContent = `${year}年`; option.onclick = () => { const month = state.dayPickerShowing.getMonth(), day = state.dayPickerShowing.getDate(), lastDay = new Date(year, month + 1, 0).getDate(); state.dayPickerShowing = new Date(year, month, Math.min(day, lastDay)); list.classList.add('is-hidden'); $('day-picker-year').setAttribute('aria-expanded', 'false'); renderDayPicker(); }; list.append(option); } }
function renderDayPicker() { const year = state.dayPickerShowing.getFullYear(), month = state.dayPickerShowing.getMonth(); $('day-picker-year-label').textContent = `${year}年`; $('day-picker-date-label').textContent = `${month + 1}月${state.dayPickerShowing.getDate()}日`; $('day-picker-month-label').textContent = `${month + 1}月`; const first = new Date(year, month, 1), start = new Date(year, month, 1 - first.getDay()), grid = $('day-picker-grid'); grid.innerHTML = ''; for (let i = 0; i < 42; i += 1) { const d = new Date(start); d.setDate(start.getDate() + i); const value = dateKey(d), button = document.createElement('button'); button.type = 'button'; button.className = `day-picker-day ${d.getMonth() === month ? '' : 'is-other'} ${value === dateKey(state.selected) ? 'is-selected' : ''} ${value === dateKey(new Date()) ? 'is-today' : ''}`; button.textContent = d.getDate(); button.setAttribute('aria-label', formatDate(d)); button.onclick = () => { state.selected = new Date(d); state.showing = new Date(d); $('day-date-dialog').close(); render(); }; grid.append(button); } renderDayYearList(); }
function openDayDatePicker() { state.dayPickerShowing = new Date(state.selected); $('day-year-list').classList.add('is-hidden'); $('day-picker-year').setAttribute('aria-expanded', 'false'); renderDayPicker(); $('day-date-dialog').showModal(); }
$('day-date-trigger').onclick = openDayDatePicker; $('close-day-date-dialog').onclick = () => $('day-date-dialog').close(); $('day-picker-previous-month').onclick = () => { state.dayPickerShowing.setMonth(state.dayPickerShowing.getMonth() - 1); renderDayPicker(); }; $('day-picker-next-month').onclick = () => { state.dayPickerShowing.setMonth(state.dayPickerShowing.getMonth() + 1); renderDayPicker(); }; $('day-picker-year').onclick = () => { const list = $('day-year-list'), expanded = list.classList.toggle('is-hidden'); $('day-picker-year').setAttribute('aria-expanded', String(!expanded)); if (!expanded) list.querySelector('.is-selected')?.scrollIntoView({ block: 'center' }); };
function renderCalendarYearList() { const list = $('calendar-year-list'), selectedYear = state.showing.getFullYear(); list.innerHTML = ''; for (let year = earliestSelectableYear; year <= latestSelectableYear; year += 1) { const option = document.createElement('button'); option.type = 'button'; option.className = `day-year-option ${year === selectedYear ? 'is-selected' : ''}`; option.textContent = `${year}年`; option.onclick = () => { state.showing = new Date(year, state.showing.getMonth(), 1); $('calendar-year-dialog').close(); renderCalendar(); }; list.append(option); } }
function openCalendarYearPicker() { renderCalendarYearList(); $('calendar-year-dialog').showModal(); $('calendar-year-list').querySelector('.is-selected')?.scrollIntoView({ block: 'center' }); }
$('calendar-month-trigger').onclick = openCalendarYearPicker; $('close-calendar-year-dialog').onclick = () => $('calendar-year-dialog').close();
$('calendar-zoom-out').onclick = () => { state.calendarZoom = Math.max(0, state.calendarZoom - 1); saveCalendarZoom(); updateCalendarZoom(); renderCalendar(); }; $('calendar-zoom-in').onclick = () => { state.calendarZoom = Math.min(calendarZoomLevels.length - 1, state.calendarZoom + 1); saveCalendarZoom(); updateCalendarZoom(); renderCalendar(); };
function displayDate(value) { return new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date(`${value}T12:00:00`)); }
function normalizeTime(value, allowEndOfDay = false) { const raw = String(value).trim(), expanded = /^\d{3,4}$/.test(raw) ? `${raw.slice(0, -2)}:${raw.slice(-2)}` : raw, match = expanded.match(/^(\d{1,2}):([0-5]\d)(?::[0-5]\d)?$/); if (!match) return ''; const hours = Number(match[1]); if (hours > 23 && !(allowEndOfDay && hours === 24)) return ''; return `${String(hours).padStart(2, '0')}:${match[2]}`; }
function formatTimeInput(input, allowEndOfDay = false) { const time = normalizeTime(input.value, allowEndOfDay); if (time) input.value = time; }
function updateScheduleSummary() { const date = $('event-date').value, time = $('event-time').value, end = $('event-end-time').value, mode = $('event-time-mode').value; $('schedule-editor-title').textContent = displayDate(date); $('schedule-editor-subtitle').textContent = mode === 'range' ? `${time}–${end} 时间段` : `${time} 提醒`; }
function renderPicker() { const year = state.pickerShowing.getFullYear(), month = state.pickerShowing.getMonth(); $('picker-month-label').textContent = `${year}年${month + 1}月`; const first = new Date(year, month, 1), start = new Date(year, month, 1 - first.getDay()), grid = $('picker-calendar-grid'); grid.innerHTML = ''; for (let i = 0; i < 42; i += 1) { const d = new Date(start); d.setDate(start.getDate() + i); const button = document.createElement('button'), value = dateKey(d); button.type = 'button'; button.className = `mini-day ${d.getMonth() === month ? '' : 'is-other'} ${value === $('event-date').value ? 'is-selected' : ''} ${value === dateKey(new Date()) ? 'is-today' : ''}`; button.textContent = d.getDate(); button.onclick = () => { $('event-date').value = value; renderPicker(); updateScheduleSummary(); }; grid.append(button); } }
function setTimeMode(mode) { const isRange = mode === 'range'; $('event-time-mode').value = mode; $('time-mode-toggle').classList.toggle('is-on', isRange); $('time-mode-toggle').setAttribute('aria-checked', String(isRange)); $('end-time-field').classList.toggle('is-hidden', !isRange); if (!isRange) $('event-end-time').value = ''; updateScheduleSummary(); }
function openScheduleEditor() { $('schedule-editor').classList.remove('is-hidden'); $('schedule-editor-trigger').setAttribute('aria-expanded', 'true'); state.pickerShowing = new Date(`${$('event-date').value}T12:00:00`); $('event-time-input').value = $('event-time').value; $('event-end-time-input').value = $('event-end-time').value || '10:00'; renderPicker(); }
function closeScheduleEditor() { $('schedule-editor').classList.add('is-hidden'); $('schedule-editor-trigger').setAttribute('aria-expanded', 'false'); }
function closeEventDialog() { closeScheduleEditor(); $('event-dialog').close(); state.editingEventId = null; }
function deleteEditingEvent() { if (!state.editingEventId) return; const id = state.editingEventId; state.events = state.events.filter((event) => event.id !== id); save(); queueOperation({ type: 'delete', id }); void flushPendingOps(); $('delete-confirm-dialog').close(); closeEventDialog(); render(); }
function setEventColor(color) { $('event-color').value = color; document.querySelectorAll('[data-event-color]').forEach((button) => { const selected = button.dataset.eventColor === color; button.classList.toggle('is-selected', selected); button.setAttribute('aria-checked', String(selected)); }); }
function openEventDialog(event = null) { const isEditing = Boolean(event), eventTime = isEditing ? (normalizeTime(event.time) || event.time) : '09:00', eventEndTime = isEditing ? (normalizeTime(event.endTime, true) || '') : '', groupId = isEditing ? eventGroupId(event) : (state.activeGroupId === 'all' ? fallbackGroupId() : state.activeGroupId); state.editingEventId = isEditing ? event.id : null; $('event-dialog-eyebrow').textContent = isEditing ? '日程详情' : '新的安排'; $('event-dialog-title').textContent = isEditing ? '编辑日程' : '添加日程'; $('save-event-button').textContent = isEditing ? '保存修改' : '保存日程'; $('delete-event-button').classList.toggle('is-hidden', !isEditing); $('event-title').value = isEditing ? event.title : ''; $('event-date').value = isEditing ? event.date : dateKey(state.selected); $('event-time').value = eventTime; $('event-end-time').value = eventEndTime; $('event-time-input').value = eventTime; $('event-end-time-input').value = eventEndTime || '10:00'; renderEventGroupOptions(groupId); setEventColor(isEditing ? (event.color || 'blue') : 'blue'); $('form-error').textContent = ''; setTimeMode(isEditing && (event.mode === 'range' || event.endTime) ? 'range' : 'reminder'); updateScheduleSummary(); $('event-dialog').showModal(); $('event-title').focus(); }
function eventToRow(event) { return { id: event.id, user_id: state.user.id, title: event.title, event_date: event.date, start_time: event.time, end_time: event.endTime || null, mode: event.mode || (event.endTime ? 'range' : 'reminder'), color: event.color || 'blue', group_id: event.groupId === 'all' ? null : event.groupId }; }
function rowToEvent(row) { return { id: row.id, title: row.title, date: row.event_date, time: normalizeTime(row.start_time) || row.start_time, endTime: normalizeTime(row.end_time, true) || '', mode: row.mode || (row.end_time ? 'range' : 'reminder'), color: row.color || 'blue', groupId: row.group_id || 'all' }; }
function groupToRow(group) { return { id: group.id, user_id: state.user.id, name: group.name, color: group.color || 'blue' }; }
function preferencesRow(settings = {}) { return { user_id: state.user.id, calendar_zoom: Math.min(2, Math.max(0, Number(settings.calendarZoom ?? state.calendarZoom) || 0)), groups_initialized: Boolean(settings.groupsInitialized ?? state.groupsInitialized) }; }
function queueOperation(operation) { if (!state.user) return; const entity = operation.entity || 'event', pending = readPending().filter((item) => (item.entity || 'event') !== entity || item.id !== operation.id); pending.push({ ...operation, entity }); writePending(pending); }
function queueGroupSnapshot() { state.groups.forEach((group) => queueOperation({ entity: 'group', type: 'upsert', id: group.id, group })); }
function queueSettingsSync() { queueOperation({ entity: 'settings', type: 'upsert', id: 'preferences', settings: { calendarZoom: state.calendarZoom, groupsInitialized: state.groupsInitialized } }); }
function setSyncStatus(message, tone = '') { const status = $('sync-status'); if (status) { status.textContent = message; status.dataset.tone = tone; } $('account-button').dataset.syncState = tone; }
async function flushPendingOps() { if (!supabaseClient || !state.user || state.syncBusy) return; const pending = readPending(); if (!pending.length) return; state.syncBusy = true; setSyncStatus('正在同步…'); let failedAt = -1; for (let index = 0; index < pending.length; index += 1) { const operation = pending[index], entity = operation.entity || 'event'; let error = null; if (entity === 'group') { if (operation.type === 'delete') ({ error } = await supabaseClient.from('schedule_groups').delete().eq('user_id', state.user.id).eq('id', operation.id)); else ({ error } = await supabaseClient.from('schedule_groups').upsert(groupToRow(operation.group), { onConflict: 'user_id,id' })); } else if (entity === 'settings') ({ error } = await supabaseClient.from('schedule_preferences').upsert(preferencesRow(operation.settings), { onConflict: 'user_id' })); else if (operation.type === 'delete') ({ error } = await supabaseClient.from('schedule_events').delete().eq('id', operation.id).eq('user_id', state.user.id)); else ({ error } = await supabaseClient.from('schedule_events').upsert(eventToRow(operation.event), { onConflict: 'id' })); if (error) { failedAt = index; break; } } writePending(failedAt === -1 ? [] : pending.slice(failedAt)); state.syncBusy = false; setSyncStatus(failedAt === -1 ? '已同步' : '暂存本机，稍后重试', failedAt === -1 ? 'ok' : 'offline'); }
async function fetchCloudGroups() { if (!supabaseClient || !state.user) return null; const { data, error } = await supabaseClient.from('schedule_groups').select('*').eq('user_id', state.user.id).order('created_at'); if (error) { setSyncStatus('暂存本机，稍后重试', 'offline'); return null; } return (data || []).map((group) => ({ id: group.id, name: group.name, color: group.color || 'blue' })); }
async function prepareCustomSync() { const localGroups = state.groups, localEvents = state.events, localGroupsStored = hasStoredGroups(), localZoomStored = localStorage.getItem(zoomStorageKey) !== null; const { data: preferences, error: preferencesError } = await supabaseClient.from('schedule_preferences').select('*').eq('user_id', state.user.id).maybeSingle(); if (preferencesError) { setSyncStatus('暂存本机，稍后重试', 'offline'); return false; } if (preferences) { state.calendarZoom = Math.min(2, Math.max(0, Number(preferences.calendar_zoom) || 0)); state.groupsInitialized = Boolean(preferences.groups_initialized); localStorage.setItem(zoomStorageKey, String(state.calendarZoom)); updateCalendarZoom(); } else state.groupsInitialized = false; const cloudGroups = await fetchCloudGroups(); if (cloudGroups === null) return false; if (state.groupsInitialized) { state.groups = cloudGroups; saveGroups(); } else if (localGroupsStored) { state.groups = localGroups; state.groupsInitialized = true; saveGroups(); queueGroupSnapshot(); queueSettingsSync(); localEvents.forEach((event) => queueOperation({ entity: 'event', type: 'upsert', id: event.id, event })); } else { state.groups = localGroups; if (!preferences && localZoomStored) queueSettingsSync(); } return true; }
async function fetchCloudEvents() { if (!supabaseClient || !state.user) return false; const { data, error } = await supabaseClient.from('schedule_events').select('*').eq('user_id', state.user.id).order('event_date').order('start_time'); if (error) { setSyncStatus('暂存本机，稍后重试', 'offline'); return false; } const pending = readPending().filter((operation) => (operation.entity || 'event') === 'event'), pendingIds = new Set(pending.map((item) => item.id)); const merged = new Map((data || []).map((row) => [row.id, rowToEvent(row)])); pending.forEach((operation) => { if (operation.type === 'delete') merged.delete(operation.id); else merged.set(operation.id, operation.event); }); state.events = Array.from(merged.values()); save(); setSyncStatus(pendingIds.size ? '暂存本机，稍后重试' : '已同步', pendingIds.size ? 'offline' : 'ok'); render(); return true; }
async function migrateLegacyEvents() { const legacy = readStoredEvents(storageKey); if (!legacy.length || !supabaseClient || !state.user) return; const { error } = await supabaseClient.from('schedule_events').upsert(legacy.map(eventToRow), { onConflict: 'id' }); if (!error) { localStorage.removeItem(storageKey); state.events = [...state.events, ...legacy.filter((event) => !state.events.some((current) => current.id === event.id))]; save(); } }
async function syncCurrentUser() { if (!state.user || !supabaseClient) { setSyncStatus(state.user ? '仅本机保存' : '未登录'); return; } setSyncStatus('正在同步…'); if (!await prepareCustomSync()) return; await migrateLegacyEvents(); await flushPendingOps(); if (state.groupsInitialized) { const cloudGroups = await fetchCloudGroups(); if (cloudGroups !== null) { state.groups = cloudGroups; saveGroups(); } } await fetchCloudEvents(); }
function showAuthReminder() { if (state.user || sessionStorage.getItem(authReminderKey)) return; sessionStorage.setItem(authReminderKey, '1'); $('sync-reminder-dialog').showModal(); }
async function handleSession(user) { const previousId = state.user?.id; state.user = user; state.authReady = true; if (!user) { state.groups = readStoredGroups(groupStorageKey()); state.activeGroupId = 'all'; state.events = readStoredEvents(storageKey); normalizeEventGroups(); updateAccountUI(); render(); showAuthReminder(); return; } if (previousId === user.id && state.events.length) return; state.groups = readStoredGroups(groupStorageKey(user)); state.activeGroupId = 'all'; state.events = readStoredEvents(userStorageKey(user)); normalizeEventGroups(); updateAccountUI(); render(); await syncCurrentUser(); }
function accountDisplayName(user = state.user) { const username = String(user?.user_metadata?.username || '').trim(); return username || (user?.email || '已登录').split('@')[0]; }
function updateAccountUI() { const signedIn = Boolean(state.user); const displayName = signedIn ? accountDisplayName() : '登录同步'; $('account-button-label').textContent = displayName; $('account-button').title = displayName; $('account-button').setAttribute('aria-label', signedIn ? `打开 ${displayName} 的账号与同步设置` : '登录并同步日程'); $('signed-out-panel').classList.toggle('is-hidden', signedIn); $('signed-in-panel').classList.toggle('is-hidden', !signedIn); if (signedIn) { $('account-email').textContent = state.user.email || ''; setSyncStatus(supabaseClient ? '正在准备同步…' : '仅本机保存'); } }
function setAuthMode(mode) { state.authMode = mode; const registering = mode === 'register'; $('auth-mode-copy').textContent = registering ? '填写用户名、邮箱并设置密码即可注册。之后在任意设备登录同一账号，日程会自动同步。' : '使用已注册的邮箱和密码登录，同一账号在手机和电脑上会显示相同的日程。'; $('auth-username-field').classList.toggle('is-hidden', !registering); $('auth-username').required = registering; if (!registering) $('auth-username').value = ''; $('auth-password-confirm-field').classList.toggle('is-hidden', !registering); $('auth-password').setAttribute('autocomplete', registering ? 'new-password' : 'current-password'); $('auth-primary-button').textContent = registering ? '注册并开始同步' : '登录'; $('auth-mode-switch').textContent = registering ? '已有账号？去登录' : '第一次使用？注册账号'; $('auth-note').textContent = registering ? '用户名必填，最多 10 个字；密码至少需要 6 位。' : '密码至少需要 6 位。日程仅属于登录的这个邮箱。'; }
function openAuthDialog(mode = 'login') { updateAccountUI(); $('auth-message').textContent = ''; $('signed-in-message').textContent = ''; if (!state.user) setAuthMode(mode); $('auth-dialog').showModal(); if (!state.user) (mode === 'register' ? $('auth-username') : $('auth-email')).focus(); }
$('add-button').onclick = () => openEventDialog(); $('close-event-dialog').onclick = closeEventDialog; $('schedule-editor-trigger').onclick = openScheduleEditor; $('close-schedule-editor').onclick = closeScheduleEditor; $('picker-previous-month').onclick = () => { state.pickerShowing.setMonth(state.pickerShowing.getMonth() - 1); renderPicker(); }; $('picker-next-month').onclick = () => { state.pickerShowing.setMonth(state.pickerShowing.getMonth() + 1); renderPicker(); }; $('time-mode-toggle').onclick = () => setTimeMode($('event-time-mode').value === 'range' ? 'reminder' : 'range'); $('event-time-input').onblur = () => formatTimeInput($('event-time-input')); $('event-end-time-input').onblur = () => formatTimeInput($('event-end-time-input'), true); document.querySelectorAll('[data-event-color]').forEach((button) => { button.onclick = () => setEventColor(button.dataset.eventColor); }); $('group-sidebar-toggle').onclick = () => setGroupDrawer(!$('app-shell').classList.contains('is-group-drawer-open')); $('group-sidebar-scrim').onclick = () => setGroupDrawer(false); $('group-sidebar-close').onclick = () => setGroupDrawer(false); $('new-group-button').onclick = () => openGroupDialog(); $('close-group-dialog').onclick = closeGroupDialog; $('delete-group-button').onclick = () => { if (state.editingGroupId) { const count = state.events.filter((event) => eventGroupId(event) === state.editingGroupId).length; $('group-delete-confirm-copy').textContent = count ? `删除后，该日程表和其中的 ${count} 项日程都会被永久删除，且无法恢复。` : '删除后，该日程表将无法恢复。'; $('group-delete-confirm-dialog').showModal(); } }; $('cancel-group-delete-button').onclick = () => $('group-delete-confirm-dialog').close(); $('confirm-group-delete-button').onclick = deleteEditingGroup; document.querySelectorAll('[data-group-color]').forEach((button) => { button.onclick = () => setGroupColor(button.dataset.groupColor); });
$('apply-schedule-editor').onclick = () => { const time = normalizeTime($('event-time-input').value), end = normalizeTime($('event-end-time-input').value, true), isRange = $('event-time-mode').value === 'range'; if (!time || (isRange && (!end || end <= time))) { $('form-error').textContent = isRange ? '请填写有效的开始和结束时间，结束时间可为 24:00' : '请按 24 小时制填写提醒时间，例如 09:00'; return; } $('event-time-input').value = time; $('event-end-time-input').value = end || $('event-end-time-input').value; $('event-time').value = time; $('event-end-time').value = isRange ? end : ''; $('form-error').textContent = ''; updateScheduleSummary(); closeScheduleEditor(); };
$('delete-event-button').onclick = () => { if (state.editingEventId) $('delete-confirm-dialog').showModal(); }; $('cancel-delete-button').onclick = () => $('delete-confirm-dialog').close(); $('confirm-delete-button').onclick = deleteEditingEvent;
$('event-form').addEventListener('submit', (event) => { event.preventDefault(); const title = $('event-title').value.trim(), time = normalizeTime($('event-time').value), mode = $('event-time-mode').value, endTime = normalizeTime($('event-end-time').value, true), groupId = $('event-group').value; if (!title) { $('form-error').textContent = '请填写日程内容'; $('event-title').focus(); return; } if (!time || (mode === 'range' && (!endTime || endTime <= time))) { $('form-error').textContent = '请先完成有效的时间安排'; return; } if (groupId !== 'all' && !state.groups.some((group) => group.id === groupId)) { $('form-error').textContent = '请选择日程表'; return; } const eventData = { title, date: $('event-date').value, time, endTime: mode === 'range' ? endTime : '', mode, color: $('event-color').value, groupId }; let savedEvent; if (state.editingEventId) { savedEvent = { ...state.events.find((item) => item.id === state.editingEventId), ...eventData }; state.events = state.events.map((item) => item.id === state.editingEventId ? savedEvent : item); } else { savedEvent = { id: crypto.randomUUID(), ...eventData }; state.events.push(savedEvent); } save(); if (state.user) { queueOperation({ type: 'upsert', id: savedEvent.id, event: savedEvent }); void flushPendingOps(); } state.selected = new Date(`${$('event-date').value}T12:00:00`); state.showing = new Date(state.selected); closeEventDialog(); render(); });
$('group-form').addEventListener('submit', (event) => { event.preventDefault(); const name = $('group-name').value.trim(), color = $('group-color').value; if (!name) { $('group-form-error').textContent = '请填写日程表名称'; $('group-name').focus(); return; } if (Array.from(name).length > 20) { $('group-form-error').textContent = '名称最多 20 个字'; $('group-name').focus(); return; } if (state.editingGroupId) state.groups = state.groups.map((group) => group.id === state.editingGroupId ? { ...group, name, color } : group); else state.groups.push({ id: crypto.randomUUID(), name, color }); saveGroups(); if (state.user) { state.groupsInitialized = true; queueGroupSnapshot(); queueSettingsSync(); void flushPendingOps(); } closeGroupDialog(); render(); });
async function authenticateWithPassword() { if (!supabaseClient) { $('auth-message').textContent = '登录服务暂时不可用，请稍后重试'; return; } const email = $('auth-email').value.trim(), password = $('auth-password').value, registering = state.authMode === 'register', username = $('auth-username').value.trim(); if (registering && !username) { $('auth-message').textContent = '请填写用户名'; $('auth-username').focus(); return; } if (registering && Array.from(username).length > 10) { $('auth-message').textContent = '用户名最多 10 个字'; $('auth-username').focus(); return; } if (!email || !email.includes('@')) { $('auth-message').textContent = '请输入有效的邮箱地址'; $('auth-email').focus(); return; } if (password.length < 6) { $('auth-message').textContent = '密码至少需要 6 位'; $('auth-password').focus(); return; } if (registering && password !== $('auth-password-confirm').value) { $('auth-message').textContent = '两次输入的密码不一致'; $('auth-password-confirm').focus(); return; } $('auth-primary-button').disabled = true; $('auth-message').textContent = registering ? '正在注册…' : '正在登录…'; const result = registering ? await supabaseClient.auth.signUp({ email, password, options: { data: { username } } }) : await supabaseClient.auth.signInWithPassword({ email, password }); $('auth-primary-button').disabled = false; if (result.error) { $('auth-message').textContent = registering ? '注册失败：该邮箱可能已经注册，或请稍后重试' : '邮箱或密码不正确'; return; } $('auth-message').textContent = result.data.session ? '登录成功，正在同步日程…' : '注册完成，请先到邮箱完成验证后再登录'; }
$('account-button').onclick = openAuthDialog; $('close-auth-dialog').onclick = () => $('auth-dialog').close(); $('auth-mode-switch').onclick = () => { const registering = state.authMode === 'login'; setAuthMode(registering ? 'register' : 'login'); $('auth-message').textContent = ''; (registering ? $('auth-username') : $('auth-email')).focus(); }; $('auth-form').addEventListener('submit', (event) => { event.preventDefault(); void authenticateWithPassword(); }); $('sync-reminder-later').onclick = () => $('sync-reminder-dialog').close(); $('sync-reminder-login').onclick = () => { $('sync-reminder-dialog').close(); openAuthDialog('login'); }; $('sync-reminder-register').onclick = () => { $('sync-reminder-dialog').close(); openAuthDialog('register'); };
$('sign-out-button').onclick = async () => { if (supabaseClient) await supabaseClient.auth.signOut(); $('auth-dialog').close(); }; $('sync-now-button').onclick = async () => { $('sync-now-button').disabled = true; await syncCurrentUser(); $('sync-now-button').disabled = false; $('signed-in-message').textContent = $('sync-status').textContent; };
if (supabaseClient) { supabaseClient.auth.onAuthStateChange((_event, session) => { void handleSession(session?.user || null); }); supabaseClient.auth.getSession().then(({ data }) => handleSession(data.session?.user || null)); } else { state.authReady = true; updateAccountUI(); showAuthReminder(); }
updateCalendarZoom(); updateAccountUI(); render(); setInterval(refreshPastEventStyles, 30000); setInterval(() => { if (state.user && !state.syncBusy) void flushPendingOps(); }, 60000);
