const storageKey = 'memory-everyday-events';
const zoomStorageKey = 'memory-everyday-calendar-scale-v2';
const pendingSyncKey = 'memory-everyday-pending-sync';
const calendarZoomLevels = [{ previewLimit: 2 }, { previewLimit: 2 }, { previewLimit: 3 }];
const supabaseUrl = 'https://ojhukmhpjovwswnmxoig.supabase.co';
const supabasePublishableKey = 'sb_publishable_vTBsX9EuhLWb7LBY7PrRlQ_OjX3sw8l';
const supabaseClient = window.supabase?.createClient(supabaseUrl, supabasePublishableKey) || null;
const state = {
  selected: new Date(), showing: new Date(), pickerShowing: new Date(), editingEventId: null,
  calendarZoom: Math.min(2, Math.max(0, Number(localStorage.getItem(zoomStorageKey)) || 0)),
  events: readStoredEvents(storageKey), user: null, authReady: false, syncBusy: false, authMode: 'login'
};
const $ = (id) => document.getElementById(id);
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const formatDate = (date) => new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(date);
function readStoredEvents(key) { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
function writeStoredEvents(key, events) { localStorage.setItem(key, JSON.stringify(events)); }
function userStorageKey(user = state.user) { return user ? `${storageKey}:${user.id}` : storageKey; }
function pendingStorageKey(user = state.user) { return user ? `${pendingSyncKey}:${user.id}` : pendingSyncKey; }
function readPending(user = state.user) { try { const value = JSON.parse(localStorage.getItem(pendingStorageKey(user)) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
function writePending(value) { if (state.user) localStorage.setItem(pendingStorageKey(), JSON.stringify(value)); }
function save() { writeStoredEvents(userStorageKey(), state.events); }
function eventsFor(date) { return state.events.filter((e) => e.date === dateKey(date)).sort((a, b) => a.time.localeCompare(b.time)); }
function eventTimeLabel(e) { return e.endTime ? `${e.time}–${e.endTime}` : e.time; }
function isEventPast(event, now = new Date()) { const deadline = event.endTime || event.time; return new Date(`${event.date}T${deadline}:00`) <= now; }
function refreshPastEventStyles() { const now = new Date(); document.querySelectorAll('[data-event-id]').forEach((element) => { const event = state.events.find((item) => item.id === element.dataset.eventId); element.classList.toggle('is-past', Boolean(event && isEventPast(event, now))); }); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]); }
function updateCalendarZoom() { $('calendar-screen').dataset.calendarZoom = String(state.calendarZoom); $('calendar-zoom-out').disabled = state.calendarZoom === 0; $('calendar-zoom-in').disabled = state.calendarZoom === calendarZoomLevels.length - 1; $('calendar-zoom-out').setAttribute('aria-label', state.calendarZoom === 0 ? '已是最小月历' : '缩小月历'); $('calendar-zoom-in').setAttribute('aria-label', state.calendarZoom === calendarZoomLevels.length - 1 ? '已是最大月历' : '放大月历'); }
function renderCalendar() {
  const year = state.showing.getFullYear(), month = state.showing.getMonth(); $('month-label').textContent = `${year}年${month + 1}月`;
  const first = new Date(year, month, 1), start = new Date(year, month, 1 - first.getDay()), grid = $('calendar-grid'); grid.innerHTML = '';
  for (let i = 0; i < 42; i += 1) {
    const d = new Date(start); d.setDate(start.getDate() + i); const sameMonth = d.getMonth() === month, dayEvents = eventsFor(d);
    const cell = document.createElement('div'); cell.className = `day-cell ${sameMonth ? '' : 'is-other'} ${dayEvents.length ? '' : 'is-empty'} ${dateKey(d) === dateKey(state.selected) ? 'is-selected' : ''} ${dateKey(d) === dateKey(new Date()) ? 'is-today' : ''}`; cell.setAttribute('role', 'button'); cell.setAttribute('tabindex', '0'); cell.setAttribute('aria-label', `${formatDate(d)}，${dayEvents.length}项日程`);
    const number = document.createElement('span'); number.className = 'day-number'; number.textContent = d.getDate(); cell.append(number);
    const previews = document.createElement('div'); previews.className = 'day-event-previews';
    dayEvents.slice(0, calendarZoomLevels[state.calendarZoom].previewLimit).forEach((event) => { const preview = document.createElement('button'); preview.type = 'button'; preview.className = `calendar-event ${event.color || 'blue'} ${isEventPast(event) ? 'is-past' : ''}`; preview.dataset.eventId = event.id; preview.setAttribute('aria-label', `${eventTimeLabel(event)} ${event.title}`); const time = document.createElement('span'); time.className = 'calendar-event-time'; time.textContent = eventTimeLabel(event); const title = document.createElement('span'); title.className = 'calendar-event-title'; title.textContent = event.title; preview.append(time, title); preview.onclick = (click) => { click.stopPropagation(); openEventDialog(event); }; previews.append(preview); });
    if (dayEvents.length > calendarZoomLevels[state.calendarZoom].previewLimit) { const more = document.createElement('span'); more.className = 'more-events'; more.textContent = `+${dayEvents.length - calendarZoomLevels[state.calendarZoom].previewLimit}项`; previews.append(more); }
    cell.append(previews); cell.onclick = () => { state.selected = d; state.showing = new Date(d); render(); }; cell.onkeydown = (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); cell.click(); } }; grid.append(cell);
  }
  const selectedCell = grid.querySelector('.is-selected'), scroller = $('calendar-scroll'), weekdays = scroller.querySelector('.weekdays'); if (selectedCell) { const viewport = scroller.getBoundingClientRect(), cell = selectedCell.getBoundingClientRect(), headerHeight = weekdays.offsetHeight + 9, selectedCenterX = scroller.scrollLeft + cell.left - viewport.left + cell.width / 2, selectedCenterY = scroller.scrollTop + cell.top - viewport.top + cell.height / 2; scroller.scrollLeft = Math.max(0, selectedCenterX - scroller.clientWidth / 2); scroller.scrollTop = Math.max(0, selectedCenterY - headerHeight - (scroller.clientHeight - headerHeight) / 2); }
}
function eventMarkup(e, card = false) { const time = eventTimeLabel(e); return `<div class="${card ? 'event-card' : 'agenda-item'} ${e.color || 'blue'} ${isEventPast(e) ? 'is-past' : ''}" data-event-id="${escapeHtml(e.id)}" role="button" tabindex="0"><span class="${card ? '' : 'agenda-time'}">${escapeHtml(time)}</span><div><strong class="${card ? '' : 'agenda-title'}">${escapeHtml(e.title)}</strong>${card ? `<small>${e.mode === 'range' ? '时间段' : `${escapeHtml(time)} 提醒`}</small>` : ''}</div></div>`; }
function bindEventDetails() { document.querySelectorAll('.agenda-item[data-event-id], .event-card[data-event-id]').forEach((element) => { const open = () => { const event = state.events.find((item) => item.id === element.dataset.eventId); if (event) openEventDialog(event); }; element.onclick = open; element.onkeydown = (keyEvent) => { if (keyEvent.key === 'Enter' || keyEvent.key === ' ') { keyEvent.preventDefault(); open(); } }; }); }
function renderAgenda() { const events = eventsFor(state.selected); $('selected-date-label').textContent = formatDate(state.selected); $('schedule-count').textContent = events.length ? `${events.length} 项日程` : ''; $('calendar-agenda').innerHTML = events.length ? events.map((e) => eventMarkup(e)).join('') : '<div class="empty-state">这一天还没有安排，点右下角加一个吧</div>'; bindEventDetails(); }
function renderDay() { const d = state.selected; $('day-weekday').textContent = new Intl.DateTimeFormat('zh-CN', { weekday: 'long' }).format(d); $('day-title').textContent = new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric' }).format(d); const events = eventsFor(d); $('day-summary').textContent = events.length ? `今天有 ${events.length} 项安排` : '今天留给自己慢慢安排'; let html = ''; for (let h = 6; h <= 22; h += 1) { const time = `${String(h).padStart(2, '0')}:00`; html += `<div class="time-row"><span class="time-label">${time}</span><div class="time-line"></div>${events.filter((e) => e.time.slice(0, 2) === String(h).padStart(2, '0')).map((e) => eventMarkup(e, true)).join('')}</div>`; } $('timeline').innerHTML = html; bindEventDetails(); }
function render() { renderCalendar(); renderAgenda(); renderDay(); refreshPastEventStyles(); }
document.querySelectorAll('.tab').forEach((tab) => { tab.onclick = () => { document.querySelectorAll('.tab').forEach((t) => t.classList.remove('is-active')); tab.classList.add('is-active'); document.querySelectorAll('.screen').forEach((s) => s.classList.toggle('is-hidden', s.id !== tab.dataset.screen)); }; });
$('previous-month').onclick = () => { state.showing.setMonth(state.showing.getMonth() - 1); renderCalendar(); }; $('next-month').onclick = () => { state.showing.setMonth(state.showing.getMonth() + 1); renderCalendar(); }; $('today-button').onclick = $('jump-today').onclick = () => { state.selected = new Date(); state.showing = new Date(); render(); };
$('calendar-zoom-out').onclick = () => { state.calendarZoom = Math.max(0, state.calendarZoom - 1); localStorage.setItem(zoomStorageKey, String(state.calendarZoom)); updateCalendarZoom(); renderCalendar(); }; $('calendar-zoom-in').onclick = () => { state.calendarZoom = Math.min(calendarZoomLevels.length - 1, state.calendarZoom + 1); localStorage.setItem(zoomStorageKey, String(state.calendarZoom)); updateCalendarZoom(); renderCalendar(); };
function displayDate(value) { return new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date(`${value}T12:00:00`)); }
function isValidTime(value) { return /^([01]\d|2[0-3]):[0-5]\d$/.test(value); }
function updateScheduleSummary() { const date = $('event-date').value, time = $('event-time').value, end = $('event-end-time').value, mode = $('event-time-mode').value; $('schedule-editor-title').textContent = displayDate(date); $('schedule-editor-subtitle').textContent = mode === 'range' ? `${time}–${end} 时间段` : `${time} 提醒`; }
function renderPicker() { const year = state.pickerShowing.getFullYear(), month = state.pickerShowing.getMonth(); $('picker-month-label').textContent = `${year}年${month + 1}月`; const first = new Date(year, month, 1), start = new Date(year, month, 1 - first.getDay()), grid = $('picker-calendar-grid'); grid.innerHTML = ''; for (let i = 0; i < 42; i += 1) { const d = new Date(start); d.setDate(start.getDate() + i); const button = document.createElement('button'), value = dateKey(d); button.type = 'button'; button.className = `mini-day ${d.getMonth() === month ? '' : 'is-other'} ${value === $('event-date').value ? 'is-selected' : ''} ${value === dateKey(new Date()) ? 'is-today' : ''}`; button.textContent = d.getDate(); button.onclick = () => { $('event-date').value = value; renderPicker(); updateScheduleSummary(); }; grid.append(button); } }
function setTimeMode(mode) { const isRange = mode === 'range'; $('event-time-mode').value = mode; $('time-mode-toggle').classList.toggle('is-on', isRange); $('time-mode-toggle').setAttribute('aria-checked', String(isRange)); $('end-time-field').classList.toggle('is-hidden', !isRange); if (!isRange) $('event-end-time').value = ''; updateScheduleSummary(); }
function openScheduleEditor() { $('schedule-editor').classList.remove('is-hidden'); $('schedule-editor-trigger').setAttribute('aria-expanded', 'true'); state.pickerShowing = new Date(`${$('event-date').value}T12:00:00`); $('event-time-input').value = $('event-time').value; $('event-end-time-input').value = $('event-end-time').value || '10:00'; renderPicker(); }
function closeScheduleEditor() { $('schedule-editor').classList.add('is-hidden'); $('schedule-editor-trigger').setAttribute('aria-expanded', 'false'); }
function closeEventDialog() { closeScheduleEditor(); $('event-dialog').close(); state.editingEventId = null; }
function setEventColor(color) { $('event-color').value = color; document.querySelectorAll('[data-event-color]').forEach((button) => { const selected = button.dataset.eventColor === color; button.classList.toggle('is-selected', selected); button.setAttribute('aria-checked', String(selected)); }); }
function openEventDialog(event = null) { const isEditing = Boolean(event); state.editingEventId = isEditing ? event.id : null; $('event-dialog-eyebrow').textContent = isEditing ? '日程详情' : '新的安排'; $('event-dialog-title').textContent = isEditing ? '编辑日程' : '添加日程'; $('save-event-button').textContent = isEditing ? '保存修改' : '保存日程'; $('delete-event-button').classList.toggle('is-hidden', !isEditing); $('event-title').value = isEditing ? event.title : ''; $('event-date').value = isEditing ? event.date : dateKey(state.selected); $('event-time').value = isEditing ? event.time : '09:00'; $('event-end-time').value = isEditing ? (event.endTime || '') : ''; $('event-time-input').value = $('event-time').value; $('event-end-time-input').value = $('event-end-time').value || '10:00'; setEventColor(isEditing ? (event.color || 'blue') : 'blue'); $('form-error').textContent = ''; setTimeMode(isEditing && (event.mode === 'range' || event.endTime) ? 'range' : 'reminder'); updateScheduleSummary(); $('event-dialog').showModal(); $('event-title').focus(); }
function eventToRow(event) { return { id: event.id, user_id: state.user.id, title: event.title, event_date: event.date, start_time: event.time, end_time: event.endTime || null, mode: event.mode || (event.endTime ? 'range' : 'reminder'), color: event.color || 'blue' }; }
function rowToEvent(row) { return { id: row.id, title: row.title, date: row.event_date, time: row.start_time, endTime: row.end_time || '', mode: row.mode || (row.end_time ? 'range' : 'reminder'), color: row.color || 'blue' }; }
function queueOperation(operation) { if (!state.user) return; const pending = readPending().filter((item) => item.id !== operation.id); pending.push(operation); writePending(pending); }
function setSyncStatus(message, tone = '') { const status = $('sync-status'); if (status) { status.textContent = message; status.dataset.tone = tone; } $('account-button').dataset.syncState = tone; }
async function flushPendingOps() { if (!supabaseClient || !state.user || state.syncBusy) return; const pending = readPending(); if (!pending.length) return; state.syncBusy = true; setSyncStatus('正在同步…'); let failedAt = -1; for (let index = 0; index < pending.length; index += 1) { const operation = pending[index]; let error = null; if (operation.type === 'delete') { ({ error } = await supabaseClient.from('schedule_events').delete().eq('id', operation.id).eq('user_id', state.user.id)); } else { ({ error } = await supabaseClient.from('schedule_events').upsert(eventToRow(operation.event), { onConflict: 'id' })); } if (error) { failedAt = index; break; } } writePending(failedAt === -1 ? [] : pending.slice(failedAt)); state.syncBusy = false; setSyncStatus(failedAt === -1 ? '已同步' : '暂存本机，稍后重试', failedAt === -1 ? 'ok' : 'offline'); }
async function fetchCloudEvents() { if (!supabaseClient || !state.user) return false; const { data, error } = await supabaseClient.from('schedule_events').select('*').eq('user_id', state.user.id).order('event_date').order('start_time'); if (error) { setSyncStatus('暂存本机，稍后重试', 'offline'); return false; } const pending = readPending(), pendingIds = new Set(pending.map((item) => item.id)); const merged = new Map((data || []).map((row) => [row.id, rowToEvent(row)])); pending.forEach((operation) => { if (operation.type === 'delete') merged.delete(operation.id); else merged.set(operation.id, operation.event); }); state.events = Array.from(merged.values()); save(); setSyncStatus(pendingIds.size ? '暂存本机，稍后重试' : '已同步', pendingIds.size ? 'offline' : 'ok'); render(); return true; }
async function migrateLegacyEvents() { const legacy = readStoredEvents(storageKey); if (!legacy.length || !supabaseClient || !state.user) return; const { error } = await supabaseClient.from('schedule_events').upsert(legacy.map(eventToRow), { onConflict: 'id' }); if (!error) { localStorage.removeItem(storageKey); state.events = [...state.events, ...legacy.filter((event) => !state.events.some((current) => current.id === event.id))]; save(); } }
async function syncCurrentUser() { if (!state.user || !supabaseClient) { setSyncStatus(state.user ? '仅本机保存' : '未登录'); return; } setSyncStatus('正在同步…'); await migrateLegacyEvents(); await flushPendingOps(); await fetchCloudEvents(); }
async function handleSession(user) { const previousId = state.user?.id; state.user = user; state.authReady = true; if (!user) { state.events = readStoredEvents(storageKey); updateAccountUI(); render(); return; } if (previousId === user.id && state.events.length) return; state.events = readStoredEvents(userStorageKey(user)); updateAccountUI(); render(); await syncCurrentUser(); }
function updateAccountUI() { const signedIn = Boolean(state.user); $('account-button-label').textContent = signedIn ? (state.user.email || '已登录').split('@')[0] : '登录同步'; $('account-button').setAttribute('aria-label', signedIn ? '打开账号与同步设置' : '登录并同步日程'); $('signed-out-panel').classList.toggle('is-hidden', signedIn); $('signed-in-panel').classList.toggle('is-hidden', !signedIn); if (signedIn) { $('account-email').textContent = state.user.email || ''; setSyncStatus(supabaseClient ? '正在准备同步…' : '仅本机保存'); } }
function setAuthMode(mode) { state.authMode = mode; const registering = mode === 'register'; $('auth-mode-copy').textContent = registering ? '第一次使用时，填写邮箱并设置密码即可注册。之后在任意设备登录同一账号，日程会自动同步。' : '使用已注册的邮箱和密码登录，同一账号在手机和电脑上会显示相同的日程。'; $('auth-password-confirm-field').classList.toggle('is-hidden', !registering); $('auth-password').setAttribute('autocomplete', registering ? 'new-password' : 'current-password'); $('auth-primary-button').textContent = registering ? '注册并开始同步' : '登录'; $('auth-mode-switch').textContent = registering ? '已有账号？去登录' : '第一次使用？注册账号'; }
function openAuthDialog() { updateAccountUI(); $('auth-message').textContent = ''; $('signed-in-message').textContent = ''; if (!state.user) setAuthMode('login'); $('auth-dialog').showModal(); if (!state.user) $('auth-email').focus(); }
$('add-button').onclick = () => openEventDialog(); $('close-event-dialog').onclick = closeEventDialog; $('schedule-editor-trigger').onclick = openScheduleEditor; $('close-schedule-editor').onclick = closeScheduleEditor; $('picker-previous-month').onclick = () => { state.pickerShowing.setMonth(state.pickerShowing.getMonth() - 1); renderPicker(); }; $('picker-next-month').onclick = () => { state.pickerShowing.setMonth(state.pickerShowing.getMonth() + 1); renderPicker(); }; $('time-mode-toggle').onclick = () => setTimeMode($('event-time-mode').value === 'range' ? 'reminder' : 'range'); document.querySelectorAll('[data-event-color]').forEach((button) => { button.onclick = () => setEventColor(button.dataset.eventColor); });
$('apply-schedule-editor').onclick = () => { const time = $('event-time-input').value.trim(), end = $('event-end-time-input').value.trim(), isRange = $('event-time-mode').value === 'range'; if (!isValidTime(time) || (isRange && (!isValidTime(end) || end <= time))) { $('form-error').textContent = isRange ? '请填写有效的开始和结束时间' : '请按 09:00 的格式填写提醒时间'; return; } $('event-time').value = time; $('event-end-time').value = isRange ? end : ''; $('form-error').textContent = ''; updateScheduleSummary(); closeScheduleEditor(); };
$('delete-event-button').onclick = () => { if (!state.editingEventId) return; const id = state.editingEventId; state.events = state.events.filter((event) => event.id !== id); save(); queueOperation({ type: 'delete', id }); void flushPendingOps(); closeEventDialog(); render(); };
$('event-form').addEventListener('submit', (event) => { event.preventDefault(); const title = $('event-title').value.trim(), time = $('event-time').value, mode = $('event-time-mode').value, endTime = $('event-end-time').value; if (!title) { $('form-error').textContent = '请填写日程内容'; $('event-title').focus(); return; } if (!isValidTime(time) || (mode === 'range' && (!isValidTime(endTime) || endTime <= time))) { $('form-error').textContent = '请先完成有效的时间安排'; return; } const eventData = { title, date: $('event-date').value, time, endTime, mode, color: $('event-color').value }; let savedEvent; if (state.editingEventId) { savedEvent = { ...state.events.find((item) => item.id === state.editingEventId), ...eventData }; state.events = state.events.map((item) => item.id === state.editingEventId ? savedEvent : item); } else { savedEvent = { id: crypto.randomUUID(), ...eventData }; state.events.push(savedEvent); } save(); if (state.user) { queueOperation({ type: 'upsert', id: savedEvent.id, event: savedEvent }); void flushPendingOps(); } state.selected = new Date(`${$('event-date').value}T12:00:00`); state.showing = new Date(state.selected); closeEventDialog(); render(); });
async function authenticateWithPassword() { if (!supabaseClient) { $('auth-message').textContent = '登录服务暂时不可用，请稍后重试'; return; } const email = $('auth-email').value.trim(), password = $('auth-password').value; if (!email || !email.includes('@')) { $('auth-message').textContent = '请输入有效的邮箱地址'; $('auth-email').focus(); return; } if (password.length < 6) { $('auth-message').textContent = '密码至少需要 6 位'; $('auth-password').focus(); return; } const registering = state.authMode === 'register'; if (registering && password !== $('auth-password-confirm').value) { $('auth-message').textContent = '两次输入的密码不一致'; $('auth-password-confirm').focus(); return; } $('auth-primary-button').disabled = true; $('auth-message').textContent = registering ? '正在注册…' : '正在登录…'; const result = registering ? await supabaseClient.auth.signUp({ email, password }) : await supabaseClient.auth.signInWithPassword({ email, password }); $('auth-primary-button').disabled = false; if (result.error) { $('auth-message').textContent = registering ? '注册失败：该邮箱可能已经注册，或请稍后重试' : '邮箱或密码不正确'; return; } $('auth-message').textContent = result.data.session ? '登录成功，正在同步日程…' : '注册完成，请先到邮箱完成验证后再登录'; }
$('account-button').onclick = openAuthDialog; $('close-auth-dialog').onclick = () => $('auth-dialog').close(); $('auth-mode-switch').onclick = () => { setAuthMode(state.authMode === 'login' ? 'register' : 'login'); $('auth-message').textContent = ''; }; $('auth-form').addEventListener('submit', (event) => { event.preventDefault(); void authenticateWithPassword(); });
$('sign-out-button').onclick = async () => { if (supabaseClient) await supabaseClient.auth.signOut(); $('auth-dialog').close(); }; $('sync-now-button').onclick = async () => { $('sync-now-button').disabled = true; await syncCurrentUser(); $('sync-now-button').disabled = false; $('signed-in-message').textContent = $('sync-status').textContent; };
if (supabaseClient) { supabaseClient.auth.onAuthStateChange((_event, session) => { void handleSession(session?.user || null); }); supabaseClient.auth.getSession().then(({ data }) => handleSession(data.session?.user || null)); } else { state.authReady = true; updateAccountUI(); }
updateCalendarZoom(); updateAccountUI(); render(); setInterval(refreshPastEventStyles, 30000); setInterval(() => { if (state.user && !state.syncBusy) void flushPendingOps(); }, 60000);
