const storageKey = 'memory-everyday-events';
const zoomStorageKey = 'memory-everyday-calendar-scale-v2';
const calendarZoomLevels = [{previewLimit:2},{previewLimit:2},{previewLimit:3}];
const state = { selected: new Date(), showing: new Date(), pickerShowing: new Date(), editingEventId: null, calendarZoom: Math.min(2,Math.max(0,Number(localStorage.getItem(zoomStorageKey))||0)), events: JSON.parse(localStorage.getItem(storageKey) || '[]') };
const $ = (id) => document.getElementById(id);
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const formatDate = (date) => new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(date);
const save = () => localStorage.setItem(storageKey, JSON.stringify(state.events));
function eventsFor(date){return state.events.filter(e=>e.date===dateKey(date)).sort((a,b)=>a.time.localeCompare(b.time));}
function eventTimeLabel(e){return e.endTime?`${e.time}–${e.endTime}`:e.time}
function isEventPast(event,now=new Date()){const deadline=event.endTime||event.time;return new Date(`${event.date}T${deadline}:00`)<=now}
function refreshPastEventStyles(){const now=new Date();document.querySelectorAll('[data-event-id]').forEach(element=>{const event=state.events.find(item=>item.id===element.dataset.eventId);element.classList.toggle('is-past',Boolean(event&&isEventPast(event,now)))})}
function updateCalendarZoom(){$('calendar-screen').dataset.calendarZoom=String(state.calendarZoom);$('calendar-zoom-out').disabled=state.calendarZoom===0;$('calendar-zoom-in').disabled=state.calendarZoom===calendarZoomLevels.length-1;$('calendar-zoom-out').setAttribute('aria-label',state.calendarZoom===0?'已是最小月历':'缩小月历');$('calendar-zoom-in').setAttribute('aria-label',state.calendarZoom===calendarZoomLevels.length-1?'已是最大月历':'放大月历')}
function renderCalendar(){
  const year=state.showing.getFullYear(), month=state.showing.getMonth();
  $('month-label').textContent=`${year}年${month+1}月`;
  const first=new Date(year,month,1), start=new Date(year,month,1-first.getDay()), grid=$('calendar-grid'); grid.innerHTML='';
  for(let i=0;i<42;i++){
    const d=new Date(start);d.setDate(start.getDate()+i);const sameMonth=d.getMonth()===month,dayEvents=eventsFor(d);
    const cell=document.createElement('div');cell.className=`day-cell ${sameMonth?'':'is-other'} ${dayEvents.length?'':'is-empty'} ${dateKey(d)===dateKey(state.selected)?'is-selected':''} ${dateKey(d)===dateKey(new Date())?'is-today':''}`;cell.setAttribute('role','button');cell.setAttribute('tabindex','0');cell.setAttribute('aria-label',`${formatDate(d)}，${dayEvents.length}项日程`);
    const number=document.createElement('span');number.className='day-number';number.textContent=d.getDate();cell.append(number);
    const previews=document.createElement('div');previews.className='day-event-previews';
    const previewLimit=calendarZoomLevels[state.calendarZoom].previewLimit;dayEvents.slice(0,previewLimit).forEach(event=>{const preview=document.createElement('button');preview.type='button';preview.className=`calendar-event ${event.color||'blue'} ${isEventPast(event)?'is-past':''}`;preview.dataset.eventId=event.id;preview.setAttribute('aria-label',`${eventTimeLabel(event)} ${event.title}`);const time=document.createElement('span');time.className='calendar-event-time';time.textContent=eventTimeLabel(event);const title=document.createElement('span');title.className='calendar-event-title';title.textContent=event.title;preview.append(time,title);preview.onclick=click=>{click.stopPropagation();openEventDialog(event)};previews.append(preview)});
    if(dayEvents.length>previewLimit){const more=document.createElement('span');more.className='more-events';more.textContent=`+${dayEvents.length-previewLimit}项`;previews.append(more)}
    cell.append(previews);cell.onclick=()=>{state.selected=d;state.showing=new Date(d);render()};cell.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();cell.click()}};grid.append(cell)
  }
  const selectedCell=grid.querySelector('.is-selected'),scroller=$('calendar-scroll'),weekdays=scroller.querySelector('.weekdays');if(selectedCell){const viewport=scroller.getBoundingClientRect(),cell=selectedCell.getBoundingClientRect(),headerHeight=weekdays.offsetHeight+9,selectedCenterX=scroller.scrollLeft+cell.left-viewport.left+cell.width/2,selectedCenterY=scroller.scrollTop+cell.top-viewport.top+cell.height/2;scroller.scrollLeft=Math.max(0,selectedCenterX-scroller.clientWidth/2);scroller.scrollTop=Math.max(0,selectedCenterY-headerHeight-(scroller.clientHeight-headerHeight)/2)}
}
function eventMarkup(e,card=false){const time=eventTimeLabel(e);return `<div class="${card?'event-card':'agenda-item'} ${e.color||'blue'} ${isEventPast(e)?'is-past':''}" data-event-id="${e.id}"><span class="${card?'':'agenda-time'}">${time}</span><div><strong class="${card?'':'agenda-title'}">${e.title}</strong>${card?`<small>${e.mode==='range'?'时间段':`${time} 提醒`}</small>`:''}</div></div>`}
function renderAgenda(){const events=eventsFor(state.selected);$('selected-date-label').textContent=formatDate(state.selected);$('schedule-count').textContent=events.length?`${events.length} 项日程`:'';$('calendar-agenda').innerHTML=events.length?events.map(e=>eventMarkup(e)).join(''):'<div class="empty-state">这一天还没有安排，点右下角加一个吧</div>'}
function renderDay(){const d=state.selected;$('day-weekday').textContent=new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(d);$('day-title').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}).format(d);const events=eventsFor(d);$('day-summary').textContent=events.length?`今天有 ${events.length} 项安排`:'今天留给自己慢慢安排';let html='';for(let h=6;h<=22;h++){const time=String(h).padStart(2,'0')+':00';html+=`<div class="time-row"><span class="time-label">${time}</span><div class="time-line"></div>${events.filter(e=>e.time.slice(0,2)===String(h).padStart(2,'0')).map(e=>eventMarkup(e,true)).join('')}</div>`}$('timeline').innerHTML=html}
function render(){renderCalendar();renderAgenda();renderDay()}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('is-active'));tab.classList.add('is-active');document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('is-hidden',s.id!==tab.dataset.screen))});
$('previous-month').onclick=()=>{state.showing.setMonth(state.showing.getMonth()-1);renderCalendar()};$('next-month').onclick=()=>{state.showing.setMonth(state.showing.getMonth()+1);renderCalendar()};$('today-button').onclick=$('jump-today').onclick=()=>{state.selected=new Date();state.showing=new Date();render()};
$('calendar-zoom-out').onclick=()=>{state.calendarZoom=Math.max(0,state.calendarZoom-1);localStorage.setItem(zoomStorageKey,String(state.calendarZoom));updateCalendarZoom();renderCalendar()};$('calendar-zoom-in').onclick=()=>{state.calendarZoom=Math.min(calendarZoomLevels.length-1,state.calendarZoom+1);localStorage.setItem(zoomStorageKey,String(state.calendarZoom));updateCalendarZoom();renderCalendar()};
function displayDate(value){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${value}T12:00:00`))}
function isValidTime(value){return /^([01]\d|2[0-3]):[0-5]\d$/.test(value)}
function updateScheduleSummary(){const date=$('event-date').value;const time=$('event-time').value;const end=$('event-end-time').value;const mode=$('event-time-mode').value;$('schedule-editor-title').textContent=displayDate(date);$('schedule-editor-subtitle').textContent=mode==='range'?`${time}–${end} 时间段`:`${time} 提醒`}
function renderPicker(){const year=state.pickerShowing.getFullYear(),month=state.pickerShowing.getMonth();$('picker-month-label').textContent=`${year}年${month+1}月`;const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay()),grid=$('picker-calendar-grid');grid.innerHTML='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const button=document.createElement('button');const value=dateKey(d);button.type='button';button.className=`mini-day ${d.getMonth()===month?'':'is-other'} ${value===$('event-date').value?'is-selected':''} ${value===dateKey(new Date())?'is-today':''}`;button.textContent=d.getDate();button.onclick=()=>{$('event-date').value=value;renderPicker();updateScheduleSummary()};grid.append(button)}}
function setTimeMode(mode){const isRange=mode==='range';$('event-time-mode').value=mode;$('time-mode-toggle').classList.toggle('is-on',isRange);$('time-mode-toggle').setAttribute('aria-checked',String(isRange));$('end-time-field').classList.toggle('is-hidden',!isRange);if(!isRange)$('event-end-time').value='';updateScheduleSummary()}
function openScheduleEditor(){$('schedule-editor').classList.remove('is-hidden');$('schedule-editor-trigger').setAttribute('aria-expanded','true');state.pickerShowing=new Date(`${$('event-date').value}T12:00:00`);$('event-time-input').value=$('event-time').value;$('event-end-time-input').value=$('event-end-time').value||'10:00';renderPicker()}
function closeScheduleEditor(){$('schedule-editor').classList.add('is-hidden');$('schedule-editor-trigger').setAttribute('aria-expanded','false')}
function closeEventDialog(){closeScheduleEditor();$('event-dialog').close();state.editingEventId=null}
function openEventDialog(event=null){const isEditing=Boolean(event);state.editingEventId=isEditing?event.id:null;$('event-dialog-eyebrow').textContent=isEditing?'日程详情':'新的安排';$('event-dialog-title').textContent=isEditing?'编辑日程':'添加日程';$('save-event-button').textContent=isEditing?'保存修改':'保存日程';$('delete-event-button').classList.toggle('is-hidden',!isEditing);$('event-title').value=isEditing?event.title:'';$('event-date').value=isEditing?event.date:dateKey(state.selected);$('event-time').value=isEditing?event.time:'09:00';$('event-end-time').value=isEditing?(event.endTime||''):'';$('event-time-input').value=$('event-time').value;$('event-end-time-input').value=$('event-end-time').value||'10:00';$('event-color').value=isEditing?(event.color||'blue'):'blue';$('form-error').textContent='';setTimeMode(isEditing&&(event.mode==='range'||event.endTime)?'range':'reminder');updateScheduleSummary();$('event-dialog').showModal();$('event-title').focus()}
$('add-button').onclick=()=>openEventDialog();
$('close-event-dialog').onclick=closeEventDialog;$('schedule-editor-trigger').onclick=openScheduleEditor;$('close-schedule-editor').onclick=closeScheduleEditor;$('picker-previous-month').onclick=()=>{state.pickerShowing.setMonth(state.pickerShowing.getMonth()-1);renderPicker()};$('picker-next-month').onclick=()=>{state.pickerShowing.setMonth(state.pickerShowing.getMonth()+1);renderPicker()};$('time-mode-toggle').onclick=()=>setTimeMode($('event-time-mode').value==='range'?'reminder':'range');
$('apply-schedule-editor').onclick=()=>{const time=$('event-time-input').value.trim(),end=$('event-end-time-input').value.trim(),isRange=$('event-time-mode').value==='range';if(!isValidTime(time)||(isRange&&(!isValidTime(end)||end<=time))){$('form-error').textContent=isRange?'请填写有效的开始和结束时间':'请按 09:00 的格式填写提醒时间';return}$('event-time').value=time;$('event-end-time').value=isRange?end:'';$('form-error').textContent='';updateScheduleSummary();closeScheduleEditor()};
$('delete-event-button').onclick=()=>{if(!state.editingEventId)return;state.events=state.events.filter(event=>event.id!==state.editingEventId);save();closeEventDialog();render()};
$('event-form').addEventListener('submit',e=>{e.preventDefault();const title=$('event-title').value.trim(),time=$('event-time').value,mode=$('event-time-mode').value,endTime=$('event-end-time').value;if(!title){$('form-error').textContent='请填写日程内容';$('event-title').focus();return}if(!isValidTime(time)||(mode==='range'&&(!isValidTime(endTime)||endTime<=time))){$('form-error').textContent='请先完成有效的时间安排';return}const eventData={title,date:$('event-date').value,time,endTime,mode,color:$('event-color').value};if(state.editingEventId){state.events=state.events.map(event=>event.id===state.editingEventId?{...event,...eventData}:event)}else{state.events.push({id:crypto.randomUUID(),...eventData})}save();state.selected=new Date($('event-date').value+'T12:00:00');state.showing=new Date(state.selected);closeEventDialog();render()});
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js');updateCalendarZoom();render();setInterval(refreshPastEventStyles,30000);
